apiVersion: v1
kind: Service
metadata:
  name: {{ template "geth.fullname" . }}
  labels:
    app: {{ template "geth.name" . }}
    chart: {{ template "geth.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8545
      targetPort: geth
      protocol: TCP
      name: geth
    - port: 30303
      targetPort: geth-gossip
      protocol: TCP
      name: geth-gossip
  selector:
    app: {{ template "geth.name" . }}
    release: {{ .Release.Name }}
